name: Deploy MySQL Docker Image

on:
    push:
      branches:
        - main
  

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]  # Exemplo com label adicional
    steps:
      # Login no Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      # Pull da nova imagem Docker
      - name: Pull Docker image
        run: docker pull melissaneves/mysql-docker:latest

      # Parar o contêiner em execução (se existir)
      - name: Stop Docker container (if running)
        run: |
          if docker ps -q --filter "name=mysql-docker"; then
            docker stop mysql-docker
          else
            echo "Container not running"
          fi

      # Remover o contêiner antigo (se existir)
      - name: Remove Docker container (if exists)
        run: |
          if docker ps -aq --filter "name=mysql-docker"; then
            docker rm mysql-docker
          else
            echo "Container does not exist"
          fi

      # Iniciar um novo contêiner
      - name: Run new Docker container
        run: docker run --name mysql-docker -d -p 3306:3306 melissaneves/mysql-docker:latest
