name: Build and Push MySQL Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout o código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Configuração do QEMU (para builds multiplataforma, se necessário)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Configuração do Docker Buildx (para builds avançados)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construir e publicar a imagem Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: melissaneves/mysql-docker:latest
